<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link href="<?php pandaRes('/lib/img/favicon_panda_head_96px.png'); ?>" rel="icon" />
<title><?php panda($sPageTitle); ?></title>
<link href="<?php pandaRes('/lib/css/bootstrap/3.3.0.min.css'); ?>" rel="stylesheet" />
<link href="<?php pandaRes('/lib/suit/myboot/global.css'); ?>" rel="stylesheet" />
<?php foreach($aCssFiles as $sFile){ ?>
<link href="<?php pandaRes($sFile); ?>" rel="stylesheet" />
<?php } ?>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php panda($aTopUrl['sHome']); ?>">匠心百科</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li <?php if('www'==$sShowTap){ ?> class="active" <?php } ?>>
                        <a href="<?php panda($aTopUrl['sWWW']); ?>">首页</a>
                    </li>
                    <li <?php if('wiki'==$sShowTap){ ?> class="active" <?php } ?>>
                        <a href="<?php panda($aTopUrl['sWiki']); ?>">百科</a>
                    </li>
                    <li <?php if('mall'==$sShowTap){ ?> class="active" <?php } ?>>
                        <a href="<?php panda($aTopUrl['sMall']); ?>">商城</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown<?php if('member'==$sShowTap){ ?> active<?php } ?>">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            用户中心
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="<?php panda($aTopUrl['aMember']['sHome']); ?>">用户首页</a>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">账户与安全</li>
                            <li>
                                <a href="<?php panda($aTopUrl['aMember']['aInfo']['sEditBase']); ?>">修改基本信息</a>
                            </li>
                            <li>
                                <a href="<?php panda($aTopUrl['aMember']['aInfo']['sEditPwd']); ?>">修改密码</a>
                            </li>
                            <li>
                                <a href="<?php panda($aTopUrl['aMember']['aInfo']['sBindMobile']); ?>">绑定手机</a>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">我的积分</li>
                            <li>
                                <a href="<?php panda($aTopUrl['aMember']['aScore']['sHome']); ?>">积分首页</a>
                            </li>
                            <li>
                                <a href="<?php panda($aTopUrl['aMember']['aScore']['sListing']); ?>">积分记录</a>
                            </li>
                        </ul>
                    </li>
                    <li class="active">
                        <a href="#" class="backtotop">返回顶部</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container pagecontent">