<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="">
<meta name="author" content="">
<link href="<?php pandaRes('/lib/img/favicon_panda_head_96px.png'); ?>" rel="icon" />
<title>PC网站的首页</title>
<link href="<?php pandaRes('/lib/css/bootstrap/3.3.0.min.css'); ?>" rel="stylesheet" />
<style type="text/css">
.foot {
	background-color: #f8f8f8;
	border-style: solid;
	border-color: #e7e7e7;
	border-width: 1px 0px 0px;
	margin-top: 20px;
	height: 50px;
	line-height: 50px;
	text-align: center;
}

.bodycontainer {
	padding: 15px;
	border-radius: 6px;
	border: 1px solid #e7e7e7;
	margin-top: 70px;
	line-height: 50px;
	text-align: center;
}
</style>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">网站名</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="#">首页</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="#">返回顶部</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="bodycontainer">这是一个PC网站的首页</div>
    </div>
    <div class="foot">网站备案编号</div>
    <script src="<?php pandaRes('/lib/js/jquery/3.1.0.min.js'); ?>"></script>
    <script src="<?php pandaRes('/lib/js/bootstrap/3.3.0.min.js'); ?>"></script>
</body>
</html>