<?php
$this->pandaTpl('/global/top', array(
    'sPageTitle' => '卧龙苑-管理-首页',
    'aCssFiles' => [],
    'sShowTap' => 'manage'
));
?>
<div class="col-sm-2">
    <div class="panel panel-primary">
        <?php $this->pandaTpl('/manage/global/left'); ?>
    </div>
</div>
<div class="col-sm-10">
    <ol class="breadcrumb">
        <?php $aCrumbUrls[0][0]='Dashboard';$this->pandaTpl('/manage/global/breadcrumb',['aCrumbUrls'=>$aCrumbUrls]); ?>
    </ol>
    <div>内容12345<?php //pandaLang(); ?></div>
</div>
<?php
$this->pandaTpl('/global/bottom', array(
    'aJSFiles' => []
));
