<?php $this->pandaTpl('component_top',array('sPageTitle' => '黑白配-首页','aCssFiles'=>[],'sShowTap'=>'default')); ?>
<div class="page-header">
    <h1>编辑器说明</h1>
</div>
<h3>主要标签</h3>
<table class="table table-hover table-striped">
    <thead>
        <tr>
            <td>代码</td>
            <td>实例</td>
        </tr>
    </thead>
    <tbody>
        <?php $sCode='<p style="font-size: 24px; color: #ff0;">这是大段落分割</p>'; ?>
        <tr>
            <td><?php panda($sCode); ?></td>
            <td><?php pandaHtml($sCode); ?></td>
        </tr>
        <?php $sCode='<p style="text-indent: 28px; color: #ff0;">这是小段落分割</p>'; ?>
        <tr>
            <td><?php panda($sCode); ?></td>
            <td><?php pandaHtml($sCode); ?></td>
        </tr>
        <?php $sCode='<p style="text-indent: 28px">这是一段普通文字</p>'; ?>
        <tr>
            <td><?php panda($sCode); ?></td>
            <td><?php pandaHtml($sCode); ?></td>
        </tr>
        <?php $sCode='<p style="text-align: center">这是居中的图片或者文字</p>'; ?>
        <tr>
            <td><?php panda($sCode); ?></td>
            <td><?php pandaHtml($sCode); ?></td>
        </tr>
    </tbody>
</table>
<h3>图片尺寸</h3>
<table class="table table-hover">
    <thead>
        <tr>
            <td>排版</td>
            <td>尺寸</td>
            <td>用途</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan="5">横向</td>
            <td>830x*</td>
            <td>固定尺寸,一张宽度超过830的全景照片使用</td>
        </tr>
        <tr>
            <td>830x623</td>
            <td>原始尺寸,一张横照片使用</td>
        </tr>
        <tr>
            <td>427x320</td>
            <td>一半尺寸,一张横照片使用</td>
        </tr>
        <tr>
            <td>285x213</td>
            <td>1/3尺寸,横照片并排两张居中时使用</td>
        </tr>
        <tr>
            <td>213x160</td>
            <td>1/4尺寸,横照片并排三张居中时使用</td>
        </tr>
        <tr>
            <td rowspan="4">纵向</td>
            <td>640x853</td>
            <td>原始尺寸,竖照片一张居中时使用</td>
        </tr>
        <tr>
            <td>320x427</td>
            <td>一半尺寸,竖照片并排两张居中时使用</td>
        </tr>
        <tr>
            <td>213x285</td>
            <td>1/3尺寸,竖照片并排三张居中时使用</td>
        </tr>
        <tr>
            <td>160x213</td>
            <td>1/4尺寸,横照片并排四张居中时使用</td>
        </tr>
        <tr>
            <td rowspan="3">混排</td>
            <td>240x320</td>
            <td>竖照片与427x320横照片并排时使用</td>
        </tr>
        <tr>
            <td>160x213</td>
            <td>竖照片与285x213横照片并排时使用</td>
        </tr>
        <tr>
            <td>120x160</td>
            <td>竖照片与213x160横照片并排时使用</td>
        </tr>
        <tr>
            <td>外边距</td>
            <td>*</td>
            <td>一张照片一排时,是10px,两张及以上照片一排时,是5px,浮动照片无论几张一排,均是10px</td>
        </tr>
    </tbody>
</table>
<?php $this->pandaTpl('component_bottom',array('aJSFiles'=>[])); ?>