<?php
$this->pandaTpl('/global/top', array(
    'sPageTitle' => '匠心百科-首页',
    'aCssFiles' => [],
    'sShowTap' => 'wiki'
));
?>
<form class="form-inline text-right">
    <div class="form-group">
        <input type="text" class="form-control" id="variety" name="variety" placeholder="品种名">
    </div>
    <button type="submit" class="btn btn-default" aria-label="Left Align">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </button>
</form>
<?php
$this->pandaTpl('/global/bottom', array(
    'aJSFiles' => []
));
