<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link href="<?php pandaRes('/lib/img/favicon_panda_head_96px.png'); ?>" rel="icon" />
<title>H5网站的首页</title>
<link href="<?php pandaRes('/lib/css/bootstrap/3.3.0.min.css'); ?>" rel="stylesheet" />
<link href="<?php pandaRes('/lib/suit/myboot/global.css'); ?>" rel="stylesheet" />
<style type="text/css">
.bodycontainer {
    line-height: 50px;
}
</style>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">网站名</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="#">首页</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="#">返回顶部</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container pagecontent">这是一个H5网站的首页</div>
    <footer class="footer">
        <div class="container">
            <div class="footerinfo">网站备案编号</div>
        </div>
    </footer>
    <script src="<?php pandaRes('/lib/js/jquery/3.1.0.min.js'); ?>"></script>
    <script src="<?php pandaRes('/lib/js/bootstrap/3.3.0.min.js'); ?>"></script>
</body>
</html>