<div class="panel-heading">联系人管理</div>
<div class="list-group">
    <a href="<?php panda($aLeftUrls['sContactList']); ?>" class="list-group-item">联系人列表</a>
</div>
<div class="panel-heading">相册管理</div>
<div class="list-group">
    <a href="<?php panda($aLeftUrls['sPhotoList']); ?>" class="list-group-item">照片列表</a>
</div>
<div class="panel-heading">文档管理</div>
<div class="list-group">
    <a href="<?php panda($aLeftUrls['sDocumentList']); ?>" class="list-group-item">文档列表</a>
</div>
<div class="panel-heading">剧集管理</div>
<div class="list-group">
    <a href="<?php panda($aLeftUrls['sVideoList']); ?>" class="list-group-item">剧集列表</a>
</div>
<div class="panel-heading">数据管理</div>
<div class="list-group">
    <a href="<?php panda($aLeftUrls['sImport']); ?>" class="list-group-item">数据导入</a>
</div>