<?php $this->pandaTpl('component_top',array('sPageTitle' => '黑白配-数独工具','aCssFiles'=>['/www_web/css/sudoku.css'],'sShowTap'=>'sudoku')); ?>
<div class="page-header">
	<h1>数独工具</h1>
</div>
<form role="form" action="" method="get" autocomplete="off" enctype="application/x-www-form-urlencoded">
	<div class="sudoku_table form-group">
		<ul class="list-unstyled list-inline">
        	<?php for($iRowIndex=0;$iRowIndex<9;++$iRowIndex){?>
            <li>
				<ul class="list-unstyled list-inline">
                <?php for($iColIndex=0;$iColIndex<9;++$iColIndex){ ?>
                    <li>
                        <?php $bHighLight = (floor($iRowIndex/3)+floor($iColIndex/3))%2; ?>
						<input type="text" name="d[<?php panda($iRowIndex); ?>][<?php panda($iColIndex); ?>]" value="<?php panda($aData[$iRowIndex][$iColIndex]); ?>"
							class="form-control sudoku_input<?php if(1==$bHighLight){ ?> sudoku_input_highlight<?php } ?>" />
					</li>       
                <?php } ?>
                </ul>
			</li>
        	<?php } ?>
    	</ul>
		<div class="form-group">
			<button type="submit" class="btn btn-default">计算</button>
			<input type="hidden" name="m" value="sudoku" />
			<a href="" class="btn btn-default" role="button" target="_blank">另一份</a>
		</div>
	</div>
</form>
<?php $this->pandaTpl('component_bottom',array('aJSFiles'=>[])); ?>