<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>404</title>
<link rel="stylesheet" href="<?php tEcho(getRes('/bootstrap/3.3.4/css/bootstrap.min.css')); ?>" />
</head>
<body>
    <h1>URL Not Found</h1>
    <script src="<?php tEcho(getRes('/jquery/1.11.2/jquery.min.js')); ?>"></script>
    <script src="<?php tEcho(getRes('/bootstrap/3.3.4/js/bootstrap.min.js')); ?>"></script>
</body>
</html>