<?php $this->pandaTpl('component_top',array('sPageTitle' => '黑白配-文件管理','aCssFiles'=>['/www_web/css/sudoku.css'],'sShowTap'=>'file')); ?>
<div class="page-header">
	<h1>文件列表</h1>
	<?php if($bFound){ ?>
	<form class="form confirm_form" role="form" enctype="application/x-www-form-urlencoded" method="post" action="<?php panda($sFileListURL); ?>">
		<button type="submit" class="btn btn-default">批量更名</button>
		<input type="hidden" name="rename" value="1" />
	</form>
	<input type="hidden" id="confirm_msg" value="确认批量更名吗?此操作无法撤消!" />
	<?php } ?>
</div>
<p>当前管理目录:<?php panda($sVScanDir); ?></p>
<p>正则表达式:<?php panda($sPattern); ?></p>
<table class="table table-hover table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>旧文件名</th>
			<th>新文件名</th>
			<th>新路径</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($aFileList as $iIndex=> $aFile){ ?>
		<tr>
			<td><?php panda($iIndex+1); ?></td>
			<td><?php panda($aFile['sOldName']); ?></td>
			<td><?php panda($aFile['sNewName']); ?></td>
			<td><?php panda($aFile['sNewPath']); ?></td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<?php $this->pandaTpl('component_bottom',array('aJSFiles'=>[])); ?>