<?php $this->pandaTpl('component_top',array('sPageTitle' => '黑白配-记事本','aCssFiles'=>[],'sShowTap'=>'note')); ?>
<div class="page-header">
	<h1>记事本</h1>
</div>
<ul>
	<li>
		<a href="#" class="anchor" data-val="house_clean">房间卫生安排</a>
	</li>
	<li>
		<a href="#" class="anchor" data-val="time_schedule">每日时间安排</a>
	</li>
	<li>
		<a href="#" class="anchor" data-val="terrestrial_heat">地暖设置</a>
	</li>
</ul>
<div class="row">
	<div class="col-xs-8">
<?php
$aWeekDayList = [
    '周日',
    '周一',
    '周二',
    '周三',
    '周四',
    '周五',
    '周六'
];
$aCleanList = [
    '客厅餐厅过道' => [
        '人拖',
        '人吸 ',
        '人吸',
        '人拖 ',
        '人吸',
        '擦灰 ',
        '人吸'
    ],
    '厨房厕所小阳台' => [
        '人拖',
        '人吸',
        '人吸 ',
        '人拖',
        '人吸 ',
        '擦灰',
        '人吸 '
    ],
    '主卧次卧' => [
        '机拖',
        '机吸',
        '',
        '',
        '机吸 ',
        '擦灰 ',
        ''
    ],
    '楼梯及一楼' => [
        '',
        '',
        '',
        '',
        '',
        '擦灰',
        '人拖'
    ],
    '影音室' => [
        '',
        '',
        '',
        '机拖',
        '',
        '擦灰',
        ''
    ],
    '储藏室' => [
        '',
        '',
        '机拖',
        '',
        '',
        '擦灰',
        ''
    ]
];
$iWeekDayIndex = date('w');
?>
		<h3 id="house_clean">
			房间卫生安排
			<small>(<?php panda($aWeekDayList[$iWeekDayIndex]); ?>)</small>
		</h3>
		<table class="table table-bordered table-hover table-striped text-center">
			<thead>
				<tr>
					<td>&nbsp;</td>
<?php foreach($aWeekDayList as $iIndex=>$sWeekDay){ ?>					
					<td <?php if($iWeekDayIndex==$iIndex){ ?> class="info" <?php } ?>><?php panda($sWeekDay); ?></td>
<?php } ?>
				</tr>
			</thead>
			<tbody>
<?php foreach($aCleanList as $sPlace=>$aWayList){ ?>			
				<tr>
					<td class="text-right"><?php panda($sPlace); ?></td>
	<?php foreach($aWayList as $iIndex=>$sWay){ ?>
					<td <?php if($iWeekDayIndex==$iIndex){ ?> class="info" <?php } ?>><?php panda($sWay); ?></td>
	<?php } ?>
				</tr>
<?php } ?>
			</tbody>
		</table>
		<h3 id="terrestrial_heat">
			地暖设置
			<small>(活跃温度:21.5,休息温度:16.5,过渡时间:半小时)</small>
		</h3>
		<table class="table table-bordered table-hover table-striped text-center">
			<thead>
				<tr>
					<td>房间</td>
					<td colspan="6">工作日</td>
					<td colspan="2">休息日</td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td rowspan="2">
						客厅
						<br />
						单休息日
					</td>
					<td class="info">06:00</td>
					<td class="info">07:00</td>
					<td class="info">11:30</td>
					<td class="info">12:30</td>
					<td class="info">19:00</td>
					<td>22:30</td>
					<td class="info">07:30</td>
					<td>22:30</td>
				</tr>
				<tr>
					<td class="info">24.5</td>
					<td class="info">22</td>
					<td class="info">22</td>
					<td class="info">22</td>
					<td class="info">22</td>
					<td>16.5</td>
					<td class="info">22</td>
					<td>16.5</td>
				</tr>
				<tr>
					<td rowspan="2">
						主卧
						<br />
						双休息日
					</td>
					<td>07:00</td>
					<td>08:00</td>
					<td>11:30</td>
					<td>12:30</td>
					<td>17:00</td>
					<td class="info">19:30</td>
					<td>08:30</td>
					<td class="info">19:30</td>
				</tr>
				<tr>
					<td>16.5</td>
					<td>16.5</td>
					<td>16.5</td>
					<td>16.5</td>
					<td>16.5</td>
					<td class="info">21.5</td>
					<td>16.5</td>
					<td class="info">21.5</td>
				</tr>
				<tr>
					<td rowspan="2">
						次卧
						<br />
						无休息日
					</td>
					<td>08:00</td>
					<td>09:00</td>
					<td>11:30</td>
					<td>12:30</td>
					<td>17:00</td>
					<td class="info">22:00</td>
					<td>-</td>
					<td>-</td>
				</tr>
				<tr>
					<td>20.5</td>
					<td>20.5</td>
					<td>20.5</td>
					<td>20.5</td>
					<td>20.5</td>
					<td class="info">16.5</td>
					<td>-</td>
					<td>-</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="col-xs-4">
<?php
$aTimeScheduleList = [
    [
        'iTime' => 630,
        'sSchedule' => '起床'
    ],
    [
        'iTime' => 700,
        'sSchedule' => '多多起床'
    ],
    [
        'iTime' => 730,
        'sSchedule' => '早餐'
    ],
    [
        'iTime' => 800,
        'sSchedule' => '送幼儿园'
    ],
    [
        'iTime' => 830,
        'sSchedule' => '工作'
    ],
    [
        'iTime' => 1200,
        'sSchedule' => '午餐'
    ],
    [
        'iTime' => 1330,
        'sSchedule' => '工作'
    ],
    [
        'iTime' => 1530,
        'sSchedule' => '接幼儿园'
    ],
    [
        'iTime' => 1730,
        'sSchedule' => '晚餐'
    ],
    [
        'iTime' => 1830,
        'sSchedule' => '家务'
    ],
    [
        'iTime' => 1930,
        'sSchedule' => '多多洗漱'
    ],
    [
        'iTime' => 2030,
        'sSchedule' => '运动/洗澡'
    ],
    [
        'iTime' => 2200,
        'sSchedule' => '娱乐'
    ],
    [
        'iTime' => 2300,
        'sSchedule' => '睡觉'
    ]
];
$bHighLight = false;
$iTimeScheduleCnt = count($aTimeScheduleList);
for ($iIndex = $iTimeScheduleCnt - 1; $iIndex > - 1; -- $iIndex) {
    if (date('Gi') >= $aTimeScheduleList[$iIndex]['iTime'] and ! $bHighLight) {
        $bHighLight = $aTimeScheduleList[$iIndex]['bHighLight'] = true;
    } else {
        $aTimeScheduleList[$iIndex]['bHighLight'] = false;
    }
}
?>
		<h3 id="time_schedule">
			每日时间安排
			<small>(<?php panda(date('H:i')); ?>)</small>
		</h3>
		<table class="table table-bordered table-hover table-striped">
			<thead>
				<tr>
					<td class="text-right">时间</td>
					<td>内容</td>
				</tr>
			</thead>
			<tbody>
<?php foreach($aTimeScheduleList as $aTimeSchedule){ ?>
				<tr <?php if($aTimeSchedule['bHighLight']){ ?> class="info" <?php } ?>>
					<td class="text-right"><?php panda(substr('0'.$aTimeSchedule['iTime'],-4,2).':'.substr($aTimeSchedule['iTime'],-2)); ?></td>
					<td><?php panda($aTimeSchedule['sSchedule']); ?></td>
				</tr>
<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php $this->pandaTpl('component_bottom',array('aJSFiles'=>[])); ?>