<?php
$this->pandaTpl('/global/top', array(
    'sPageTitle' => '说明文档-文档',
    'aCssFiles' => [],
    'sShowTap' => 'default'
));
?>
<div class="page-header">
    <h1>文档目录</h1>
</div>
<ol>
    <?php foreach($aChapterList as $aChapter){ ?>
    <li>
        <a href="<?php panda($aChapter['sUrl']); ?>" class="anchor" target="doc" data-anchor-target="<?php panda($aChapter['sAnchor']); ?>"><?php panda($aChapter['sTitle']); ?></a>
    </li>
    <?php } ?>
</ol>
<?php
$this->pandaTpl('/global/bottom', array(
    'aJSFiles' => []
));
