<?php if($aFormStatus[$sFormStatusKey]===false){ ?>
<div class="form-group">
    <label for="<?php panda($sId); ?>" class="<?php panda($sLabelWidthClass) ?> control-label"><?php panda($sLabel); ?></label>
    <div class="<?php panda($sInputWidthClass); ?>">
        <input type="<?php panda($sType); ?>" class="form-control" id="<?php panda($sId); ?>" name="<?php panda($sName); ?>" placeholder="<?php panda($sPlaceHolder); ?>" value="<?php panda($aFormData[$sFormDataKey]); ?>">
    </div>
</div>
<?php }elseif($aFormStatus[$sFormStatusKey]===true){ ?>
<div class="form-group has-success has-feedback">
    <label for="<?php panda($sId); ?>" class="<?php panda($sLabelWidthClass) ?> control-label"><?php panda($sLabel); ?></label>
    <div class="<?php panda($sInputWidthClass); ?>">
        <input type="<?php panda($sType); ?>" class="form-control" id="<?php panda($sId); ?>" name="<?php panda($sName); ?>" placeholder="<?php panda($sPlaceHolder); ?>" value="<?php panda($aFormData[$sFormDataKey]); ?>">
        <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
    </div>
</div>
<?php }else{ ?>
<div class="form-group has-error has-feedback">
    <label for="<?php panda($sId); ?>" class="<?php panda($sLabelWidthClass) ?> control-label"><?php panda($sLabel); ?></label>
    <div class="<?php panda($sInputWidthClass); ?>">
        <input type="<?php panda($sType); ?>" class="form-control" id="<?php panda($sId); ?>" name="<?php panda($sName); ?>" placeholder="<?php panda($sPlaceHolder); ?>" value="<?php panda($aFormData[$sFormDataKey]); ?>">
        <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
        <span class="help-block">
        <?php
    if (isset($aErrorMsg[$aFormStatus[$sFormStatusKey]['sType']])) {
        panda($aErrorMsg[$aFormStatus[$sFormStatusKey]['sType']]);
    } else {
        panda('未知错误');
    }
    ?>
        </span>
    </div>
</div>
<?php } ?>