<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="">
<meta name="author" content="">
<link href="<?php pandaRes('/lib/img/favicon_panda_head_96px.png'); ?>" rel="icon" />
<title><?php panda($sPageTitle); ?></title>
<link href="<?php pandaRes('/lib/css/bootstrap/3.3.0.min.css'); ?>" rel="stylesheet" />
<link href="<?php pandaRes('/wolong_web/css/global.css'); ?>" rel="stylesheet" />
<?php foreach($aCssFiles as $sFile){ ?>
<link href="<?php pandaRes($sFile); ?>" rel="stylesheet" />
<?php } ?>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="<?php panda($aTopUrls['sDefault']); ?>">卧龙苑</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li <?php if('default'==$sShowTap){ ?> class="active" <?php } ?>>
						<a href="<?php panda($aTopUrls['sDefault']); ?>">首页</a>
					</li>
					<li <?php if('photo'==$sShowTap){ ?> class="active" <?php } ?>>
						<a href="<?php panda($aTopUrls['sPhotoList']); ?>">相片</a>
					</li>
					<li <?php if('document'==$sShowTap){ ?> class="active" <?php } ?>>
						<a href="<?php panda($aTopUrls['sDocList']); ?>">文件</a>
					</li>
					<li <?php if('video'==$sShowTap){ ?> class="active" <?php } ?>>
						<a href="<?php panda($aTopUrls['sVideoList']); ?>">视频</a>
					</li>
					<li <?php if('manage'==$sShowTap){ ?> class="active" <?php } ?>>
						<a href="<?php panda($aTopUrls['sManage']); ?>" target="manage">管理</a>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="active">
						<a href="#" id="backtotop">返回顶部</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container pagecontent">