<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="">
<meta name="author" content="">
<link href="<?php pandaRes('/lib/img/favicon_panda_32px.ico'); ?>" rel="icon" />
<title>测试页面</title>
<link href="<?php pandaRes('/lib/css/bootstrap/3.3.0.min.css'); ?>" rel="stylesheet" />
<style type="text/css">
body {
	padding-top: 70px;
}

.foot {
	border-top: 2px solid #eee;
	margin: 20px 0 20px;
	padding-top: 9px;
	text-align: center;
}

.bodycontainer {
	padding: 0px 30px;
	border-radius: 6px;
	border: 1px solid #eee;
	line-height: 50px;
	text-align: center;
}
</style>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">匠心多肉</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
              	<li class="active"><a href="#">发现 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">商场</a></li>
                <li><a href="#">经验</a></li>
                <li><a href="#">大全</a></li>
                <li><a href="#">嘚瑟</a></li>
              </ul>
              <form class="navbar-form navbar-left">
                <div class="form-group">
                  <input length="30" type="text" class="form-control" placeholder="Search">
                </div>
              </form>
            </div>
            <div>
            	
            </div>
        </div>
    </nav>
	<div class="container">
		<div>
			<div class="row">
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <img src="https://s-media-cache-ak0.pinimg.com/564x/54/b7/bc/54b7bc502a18ee91fa09ea3329bafc12.jpg" alt="...">
                  <div class="caption">
                    <h4>要不要字</h3>
                    <p>说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢</p>
                  </div>
                </div>
              </div>
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <img src="https://s-media-cache-ak0.pinimg.com/564x/54/b7/bc/54b7bc502a18ee91fa09ea3329bafc12.jpg" alt="...">
                  <div class="caption">
                    <h4>要不要字</h4>
                    <p>说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢</p>
                  </div>
                </div>
              </div>
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <img src="https://s-media-cache-ak0.pinimg.com/564x/54/b7/bc/54b7bc502a18ee91fa09ea3329bafc12.jpg" alt="...">
                  <div class="caption">
                    <h4>要不要字</h4>
                    <p>说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢</p>
                  </div>
                </div>
              </div>
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <img src="https://s-media-cache-ak0.pinimg.com/564x/54/b7/bc/54b7bc502a18ee91fa09ea3329bafc12.jpg" alt="...">
                  <div class="caption">
                    <h4>要不要字</h4>
                    <p>说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢</p>
                  </div>
                </div>
              </div>
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <img src="https://s-media-cache-ak0.pinimg.com/564x/54/b7/bc/54b7bc502a18ee91fa09ea3329bafc12.jpg" alt="...">
                  <div class="caption">
                    <h4>要不要字</h4>
                    <p>说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢说你呢</p>
                  </div>
                </div>
              </div>
            </div>
		</div>
	</div>
	<div class="navbar navbar-default">
		<div class="row">      
            <div class="col-md-3 text-center">
                <p><h5><strong><a href="##">匠心首页</a></strong></h5></p>
                <p><a href="##">关于我们</a></p>
            </div>
          	<div class="col-md-6 text-left">
                  <p><h5><strong><a href="##">联系与合作</a></strong></h5></p>
                  <p><a href="##">联系我们</a></p>
                  <p><a href="##">用户反馈</a></p>
                  <p><a href="##">匠心评级说明</a></p>
          	</div>
          <div class="col-md-2 text-left">
                  <p><h5><strong><a href="##">关注我们</a></strong></h5></p>
                  <p><a href="##">公众号:</a></p>
                  <p><a href="##">新浪微博</a></p>
          </div>
          
        </div>
        
    </div>
    <div class="foot bs-docs-footer">网站备案编号</div>
    
	<script src="<?php pandaRes('/lib/js/jquery/3.1.0.min.js'); ?>"></script>
	<script src="<?php pandaRes('/lib/js/bootstrap/3.3.0.min.js'); ?>"></script>
</body>
</html>