<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="renderer" content="webkit">
<meta name="description" content="<?php tEcho($sPageDesc); ?>">
<link rel="icon" href="<?php tEcho(getRes('/favicon.ico')); ?>">
<title><?php tEcho($sPageTitle); ?></title>
<link rel="stylesheet" href="<?php tEcho(getRes('/bootstrap/3.3.4/css/bootstrap.min.css')); ?>" />
</head>
<body>