<?php
/**
 * 关于bmi
 */
tLoadTpl('global_topnav', array(
    'sNavActiveKey' => 'about-bmi',
    'aCSSURLs' => array(),
    'sPageTitle' => '关于BMI',
    'aTopUrls' => $aTopUrls
));
?>
<h3>关于BMI的计算</h3>
<p>连BMI都不知道是啥??你减肥做啥?还是慢慢看看下面的节食,可能你已经...先上公式:</p>
<h4>
	BMI = 体重(公斤) / 身高
	<sup>2</sup>
	(米
	<sup>2</sup>
	)
</h4>
<p>BMI指数又叫身体质量指数,是目前国际上常用的衡量人体胖瘦程度以及是否健康的一个标准. 主要用于统计用途,当我们需要比较及分析一个人的体重对于不同高度的人所带来的健康影响时,BMI值是一个中立而可靠的指标.
	BMI是与体内脂肪总量密切相关的指标,该指标考虑了体重和身高两个因素.BMI简单,实用,可反映全身性超重和肥胖. 在测量身体因超重而面临心脏病,高血压等风险时,比单纯的以体重来认定,更具准确性.</p>
<p>
	BMI的标准不是特别统一,下面表格列举了WHO,亚洲和中国的标准.这些标准都是针对成年人,而非儿童.
	<span class="label label-default">来自百度百科</span>
</p>
<table class="table table-striped table-bordered table-hover">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>WHO标准</th>
			<th>亚洲标准</th>
			<th>中国标准</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>偏瘦</th>
			<td colspan="3">&lt;18.5</td>
		</tr>
		<tr>
			<th>正常</th>
			<td>18.5 - 24.9</td>
			<td>18.5 - 22.9</td>
			<td>18.5 - 23.9</td>
		</tr>
		<tr>
			<th>超重</th>
			<td>≥ 25</td>
			<td>≥ 23</td>
			<td>≥ 24</td>
		</tr>
		<tr>
			<th>偏胖</th>
			<td>25.0 - 29.9</td>
			<td>23.9 - 24.9</td>
			<td>24 - 27.9</td>
		</tr>
		<tr>
			<th>肥胖</th>
			<td>30.0 - 34.9</td>
			<td>25 - 29.9</td>
			<td>≥ 28</td>
		</tr>
		<tr>
			<th>重度肥胖</th>
			<td>35.0 - 39.9</td>
			<td>≥ 30.0</td>
			<td>-</td>
		</tr>
		<tr>
			<th>极重度肥胖</th>
			<td colspan="3">≥ 40.0</td>
		</tr>
	</tbody>
</table>
<p>除了BMI以外,如果男性腰围≧90厘米,女性腰围≧80厘米,也属于体重超重.</p>
<p>什么?你问我腰在哪里??你没有腰??好吧,那我告诉你,你属于肥胖,好好锻炼身体吧.</p>
<p>不过体重超重的人就不大适合有氧运动了,尝试一下器械锻炼吧</p>
<?php
tLoadTpl('global_bottom', array(
    'aJSURLs' => array()
));
?>