<?php
/**
 * 锻炼日志
 */
tLoadTpl('global_topnav', array(
    'sNavActiveKey' => 'about-dumbbell',
    'aCSSURLs' => array(),
    'sPageTitle' => '关于哑铃',
    'aTopUrl' => $aTopUrl
));
?>
<h3>哑铃</h3>
<p>先上靓照</p>
<img alt="哑铃" src="<?php pandaRes('/bodybuild/img/dumbbell.jpg'); ?>" class="img-responsive center-block img-thumbnail">
<p>哑铃是以前的同事p领导借给我的(说这话不会被他揍吧),一对的,每个都是有几组可拆卸的配种组成.2kg的4片,0.5kg的4片,一共是10kg,可以用来做力量训练</p>
<p>哑铃的几个好处</p>
<ul>
    <li>重量随意控制,避免超重符合,损伤肌肉</li>
    <li>可以控制主要锻炼的肌肉部分,更有效果</li>
    <li>尤其是对BMI指数偏高的人,希望增肌减脂,一定要使用器械来帮助自己</li>
</ul>
<?php
tLoadTpl('global_bottom', array(
    'aJSURLs' => array()
));
?>