<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="renderer" content="webkit">
<title><?php tEcho($sPageTitle);  ?></title>
<link rel="stylesheet" href="<?php tEcho(getRes('/lib/bootstrap/3.3.4/css/bootstrap.min.css')); ?>" />
<?php foreach($aCSSURLs as $sCSSURL){ ?>
<link rel="stylesheet" href="<?php tEcho(getRes($sCSSURL)); ?>" />
<?php } ?>
<link rel="shortcut icon" href="<?php tEcho(getRes('/global/favicon.ico')); ?>" />
<link rel="bookmark" href="<?php tEcho(getRes('/global/favicon.ico')); ?>" />
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?4155f224513dcf666d3988115538daad";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
</head>
<body>