<?php
$this->pandaTpl('/global/top', array(
    'sPageTitle' => '匠心多肉-首页',
    'aCssFiles' => [
        '/duorou_web/css/home.css'
    ],
    'sShowTap' => 'www'
));
?>

<?php
$this->pandaTpl('/global/underconstruction', array(
    'sPageName' => '匠心多肉-首页'
));
?>

<?php
$this->pandaTpl('/global/bottom', array(
    'aJSFiles' => [
        '/lib/js/masonry/4.2.0.pkgd.min.js',
        '/lib/js/infinitescroll/3.0.2.pkgd.min.js',
        '/duorou_web/js/home.js'
    ]
));
