<?php
$this->pandaTpl('/global/top', array(
    'sPageTitle' => '多肉管理-丢了',
    'aCssFiles' => [],
    'sShowTap' => 'default'
));
?>
<div class="page-header">
    <h1>丢了</h1>
</div>
<p>别瞎跑了,赶紧回去吧...</p>
<!-- <script type="text/javascript" src="//qzonestyle.gtimg.cn/qzone/hybrid/app/404/search_children.js" charset="utf-8" homePageUrl="http://yoursite.com/yourPage.html" homePageName="回到我的主页"></script> -->
<?php
$this->pandaTpl('/global/bottom', array(
    'aJSFiles' => []
));
