<?php
tLoadTpl('frame_head', array(
    'aCSSURLs' => array_merge(array(
        '/bodybuild/global.css'
    ), $aCSSURLs),
    'sPageTitle' => $sPageTitle
));
?>
<nav class="navbar navbar-default  navbar-fixed-top navbar-inverse">
	<div class="container" id="top">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">
				<img src="<?php tEcho(getRes('/bodybuild/img/logo.jpg')); ?>" alt="logo" width="30" class="img-circle" />
			</a>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li <?php if($sNavActiveKey=='home'){ ?> class="active" <?php } ?>>
					<a href="<?php tEcho($aTopURLs['sHomeURL']); ?>"> 首页 </a>
				</li>
				<li <?php if($sNavActiveKey=='article'){ ?> class="active" <?php } ?>>
					<a href="<?php tEcho($aTopURLs['sHomeURL']); ?>">健身文章</a>
				</li>
				<li <?php if($sNavActiveKey=='diet'){ ?> class="active" <?php } ?>>
					<a href="<?php tEcho($aTopURLs['sDietURL']); ?>">健身饮食</a>
				</li>
				<li <?php if($sNavActiveKey=='motion'){ ?> class="active" <?php } ?>>
					<a href="<?php tEcho($aTopURLs['sMotionURL']); ?>">健身动作</a>
				</li>
				<li <?php if($sNavActiveKey=='journal'){ ?> class="active" <?php } ?>>
					<a href="<?php tEcho($aTopURLs['sHomeURL']); ?>">健身日志</a>
				</li>
				<li
					class="dropdown<?php if(in_array($sNavActiveKey,array('about-treadmill','about-dumbbell','about-bmi'))){ ?> active<?php } ?>">
					<a class="dropdown-toggle a-pointer" data-toggle="dropdown" role="button" aria-expanded="false">
						关于
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu" role="menu">
						<li <?php if($sNavActiveKey=='about-treadmill'){ ?> class="active" <?php } ?>>
							<a href="<?php tEcho($aTopURLs['sAboutTreadmillURL']); ?>">跑步机</a>
						</li>
						<li class="divider"></li>
						<li <?php if($sNavActiveKey=='abount-dumbbell'){ ?> class="active" <?php } ?>>
							<a href="<?php tEcho($aTopURLs['sAboutDumbbellURL']); ?>">哑铃</a>
						</li>
						<li class="divider"></li>
						<li <?php if($sNavActiveKey=='about-bmi'){ ?> class="active" <?php } ?>>
							<a href="<?php tEcho($aTopURLs['sAboutBMIURL']); ?>">BMI</a>
						</li>
					</ul>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<a class="a-pointer" id="backtotop">回到顶部</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<div class="container">
	<div class="page-header">
		<h1>
			puffy的减肥日记
			<small>一定能成功</small>
		</h1>
	</div>
	<div class="row">
		<div class="col-md-9">